sys:
	cd ./third-party/SDL-1.2 && ./make.sh
	cd ../shared/third-party/union-commander && make -j

clean:
	cd ./third-party/SDL-1.2 && make distclean
	cd ../shared/third-party/union-commander && make -j