# rg350/makefile
sys:
	cd ../shared/third-party/DinguxCommander && make -j
	cd ../shared/third-party/gambatte-dms && PLATFORM=gcw0 ./build_minui.sh

clean:
	cd ../shared/third-party/DinguxCommander && make -j
	cd ../shared/third-party/gambatte-dms && ./clean.sh