#ifndef MLANGUAGE_H
#define MLANGUAGE_H
// generated by generate.sh

typedef struct Language {
	char* CJK;
	char* open;
	char* back;
	char* sleep;
	char* resume;
	char* act;
	char* continue_;
	char* insert;
	char* disc_num;
	char* save;
	char* load;
	char* advanced;
	char* exit;
	char* no_preview;
	char* empty_slot;
	char* wake;
	char* swap;
	char* prioritize_compatibility;
	char* prioritize_performance;
	char* recents;
	char* settings;
} Language;

void InitLanguage(Language* language);
void QuitLanguage(void);
void ResetLanguage(void);
#endif
