#ifndef MLANGUAGE_BASE_H
#define MLANGUAGE_BASE_H
// generated by generate.sh
#include "mlanguage.h"

Language base = {
	.CJK=NULL,
	.open="OPEN",
	.back="BACK",
	.sleep="SLEEP",
	.resume="RESUME",
	.act="ACT",
	.continue_="Continue",
	.insert="Insert",
	.disc_num="Disc 0",
	.save="Save",
	.load="Load",
	.advanced="Advanced",
	.exit="Exit Game",
	.no_preview="No Preview",
	.empty_slot="Empty Slot",
	.wake="To wake from sleep,\nhold L and R and press\nany other button.\nTry it now...",
	.swap="Creating new swap file,\nthis could take a minute...",
	.prioritize_compatibility="Prioritize compatibility when playing ?",
	.prioritize_performance="Prioritize performance when playing ?",
	.recents="Recently Played",
	.settings="Settings",
};

#define kLanguageKeysCount 21
char* language_keys[kLanguageKeysCount] = {
	"CJK",
	"open",
	"back",
	"sleep",
	"resume",
	"act",
	"continue_",
	"insert",
	"disc_num",
	"save",
	"load",
	"advanced",
	"exit",
	"no_preview",
	"empty_slot",
	"wake",
	"swap",
	"prioritize_compatibility",
	"prioritize_performance",
	"recents",
	"settings",
};

#endif
